# Generated by Django 3.0.8 on 2020-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
