# Generated by Django 3.0.8 on 2020-07-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0002_auto_20200714_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artigos'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
